### ISSUE TITLE
Typo in main.js referring to file causing errors

### ISSUE THREAD

**Issue by devwax** [seancrowe/JS-ChiliConnector#5]
On [line 1 of main.js](https://github.com/seancrowe/JS-ChiliConnector/blob/master/main.js#L1) the file reference `./lib/chiliConnector.js` is capitalized, but the actual file is all lower case: [`chiliconnector.js`](https://github.com/seancrowe/JS-ChiliConnector/blob/master/lib/chiliconnector.js). So the package won't work outside of a Windows environment owing to case sensitivity.

**Comment by seancrowe** [comment]
Fix in https://github.com/seancrowe/JS-ChiliConnector/pull/6
